# Generated by Django 4.0.4 on 2022-04-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipements_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipements',
            name='categories',
        ),
        migrations.AddField(
            model_name='equipements',
            name='categories',
            field=models.ManyToManyField(to='core.categories'),
        ),
    ]
