# Generated by Django 4.0.4 on 2022-04-25 12:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_equipements_categories_equipements_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.categories'),
        ),
    ]
